### ISSUE TITLE
.sublime-syntax

### ISSUE THREAD

**Issue by FichteFoll** [carsonoid/sublime_man_page_support#2]
Hi :wave: 

I made an entirely new syntax definition for groff files (with a focus on man macros) in the new `sublime-syntax` format and was wondering whether you are interested in replacing your dated syntax with that one.

It follows scope naming conventions as well as possible and supports all font modifiers that I could find, with a couple extra commands etc. The only thing to note is that it doesn't support ST2, but less than 5% of Package Control users are on that, so it shouldn't be an issue. If anything, the current tmLanguage can still be used by older builds, though I would suggest getting rid of it.

I haven't used anything else of your package, i.e. the preview mode, but if I find areas to improve I won't hesitate to propose them.

By the way, for better searchability you should include "groff" and "troff" in your repo's description.

![Example image](https://camo.githubusercontent.com/5fc186fc3ad7e421cdccc4f18ab6e3e8c0c3adaa/68747470733a2f2f78302e61742f7448582e706e67)

**Comment by carsonoid** [comment]
Thanks for the input! Make a PR with the replacement and I would be happy to test it and pull it in.
